version: "3.9"
name: test-hugeman

services:

  db-todo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - /usr/local/mongodb:/todo
    networks:
      - hugeman-backend
  
  backend:
    image: test-hugeman-go:latest
    ports:
      - 5000:5000
    environment:
      - APP_STAGE=production
      - APP_NAME=todo
      - APP_URL=:5000
      - DB_URL=mongodb://root:123456@todo-db:27017
    networks:
      - hugeman-backend
    depends_on:
      - db-todo
      
networks:
 hugeman-backend: